project:
  type: website
  output-dir: .

website:
  title: "Kashish Joshipura"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: About
      - href: experience.qmd
        text: Experience
      - href: skills.qmd
        text: Skills
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blogs
      - href: hobbies.qmd
        text: Hobbies
    right:
      - icon: github
        href: https://github.com/kashish1928
      - icon: linkedin
        href: https://linkedin.com/in/kashishjoshipura
      - icon: envelope
        href: mailto:kashishjoshipura@gmail.com

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: false
